//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaPlaybackLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MediaPlaybackLib.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new marker at current position or selected area.
        /// </summary>
        public static string AddMarker {
            get {
                return ResourceManager.GetString("AddMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buffering....
        /// </summary>
        public static string Buffering {
            get {
                return ResourceManager.GetString("Buffering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable drag in timescale.
        /// </summary>
        public static string EditLockTooltip {
            get {
                return ResourceManager.GetString("EditLockTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot play the media because there is a problem with your sound device. There might not be a sound device installed on your computer, it might be in use by another program, or it might not be functioning properly. Please contact your administrator for assistance..
        /// </summary>
        public static string ErrorAudioHardware {
            get {
                return ResourceManager.GetString("ErrorAudioHardware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot play the media. The Player might not support the file type or a required codec might not be installed on your computer. Please contact your administrator for assistance..
        /// </summary>
        public static string ErrorMediaCodec {
            get {
                return ResourceManager.GetString("ErrorMediaCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem playing the media {0}. Please contact your administrator for assistance..
        /// </summary>
        public static string ErrorMediaGeneric {
            get {
                return ResourceManager.GetString("ErrorMediaGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to play this media. Please contact your administrator for assistance..
        /// </summary>
        public static string ErrorMediaNotAuthorized {
            get {
                return ResourceManager.GetString("ErrorMediaNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn System Tags On/Off.
        /// </summary>
        public static string FilterToolTip {
            get {
                return ResourceManager.GetString("FilterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Forward.
        /// </summary>
        public static string MediaFastForward {
            get {
                return ResourceManager.GetString("MediaFastForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string MediaLoop {
            get {
                return ResourceManager.GetString("MediaLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Tag.
        /// </summary>
        public static string MediaMarkerName_SectionTag {
            get {
                return ResourceManager.GetString("MediaMarkerName_SectionTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section Tag.
        /// </summary>
        public static string MediaMarkerName_SectionTag1 {
            get {
                return ResourceManager.GetString("MediaMarkerName_SectionTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tag.
        /// </summary>
        public static string MediaMarkerName_TimeTag {
            get {
                return ResourceManager.GetString("MediaMarkerName_TimeTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Tag.
        /// </summary>
        public static string MediaMarkerName_TimeTag1 {
            get {
                return ResourceManager.GetString("MediaMarkerName_TimeTag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute.
        /// </summary>
        public static string MediaMute {
            get {
                return ResourceManager.GetString("MediaMute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        public static string MediaPlayPause {
            get {
                return ResourceManager.GetString("MediaPlayPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rewind.
        /// </summary>
        public static string MediaRewind {
            get {
                return ResourceManager.GetString("MediaRewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Forward.
        /// </summary>
        public static string MediaSkipEnd {
            get {
                return ResourceManager.GetString("MediaSkipEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Back.
        /// </summary>
        public static string MediaSkipStart {
            get {
                return ResourceManager.GetString("MediaSkipStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string MediaStop {
            get {
                return ResourceManager.GetString("MediaStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume.
        /// </summary>
        public static string MediaVolume {
            get {
                return ResourceManager.GetString("MediaVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening....
        /// </summary>
        public static string OpeningMedia {
            get {
                return ResourceManager.GetString("OpeningMedia", resourceCulture);
            }
        }
    }
}
